
title: 大雨庄周
email: jack92_liang@163.com
description: 活着就是一场修行。
url: "https://Jack126.github.io"

markdown: kramdown
timezone: Asia/Shanghai
remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
#theme: no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "<<<" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d %H:%M" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
